[package]
name = "baldore"
version = "0.1.0"
authors = ["baldore <acornssn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
csv = "1.1"

